name: "jeandle-llvm check"

on:
  pull_request_target:
    branches:
      - 'main'

jobs:

  test:
    name: "jeandle-llvm test"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: build and test
        run : |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD=X86 -DCMAKE_BUILD_TYPE=Release ../llvm
          make check-llvm -j$(nproc)

  clang-format:
    name: "clang-format check"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: clang-format
        run : |
          git remote add jeandle-main https://github.com/jeandle/jeandle-llvm.git
          git fetch --depth=1 jeandle-main
          sudo apt-get install -y clang-format
          git clang-format jeandle-main/main
