name: "jeandle-llvm check"

on:
  pull_request_target:
    branches:
      - 'main'
  workflow_call:
    inputs:
      debug-levels:
        required: false
        type: string
        default: '[ "debug", "release" ]'

jobs:

  test:
    name: "jeandle-llvm test"
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        debug-level: ${{ fromJSON(inputs.debug-levels) }}
        include:
          - debug-level: release
            flags: '-DCMAKE_BUILD_TYPE=Release'
          - debug-level: debug
            flags: '-DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS_RELWITHDEBINFO="-O3 -g"'

    steps:
      - uses: actions/checkout@v4
      - name: build and test
        run : |
          mkdir build
          cd build
          cmake -G "Unix Makefiles" -DLLVM_TARGETS_TO_BUILD=X86 ${{ matrix.flags }} ../llvm
          make check-llvm -j$(nproc)

  clang-format:
    name: "clang-format check"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: clang-format
        run : |
          git remote add jeandle-main https://github.com/jeandle/jeandle-llvm.git
          git fetch --depth=1 jeandle-main
          sudo apt-get install -y clang-format
          git clang-format jeandle-main/main
